### ISSUE TITLE
Contoso Cafe scenario not available

### ISSUE THREAD

**Issue by MohamedSahbi** [martinkearn/Content#7]
`contosocafe-v4-dotnet` branch does not exist anymore. So, the provided link is not valid
(https://github.com/Microsoft/BotFramework-Samples/tree/contosocafe-v4-dotnet/docs-samples/V4/dotnet/ContosoCafe/ContosoCafe-5-DialogsWithLUISEntities/ContosoCafe).

The post is interesting and helpful. Thanks for sharing.

**Comment by martinkearn** [comment]
Thanks - which article was this in relation to?

**Comment by MohamedSahbi** [comment]
This article http://martink.me/articles/bot-framework-v4-what-i-learnt-in-4-days-in-july-2018

**Comment by martinkearn** [comment]
OK, that article is mostly out of date now anyway because it relates to an pre-released version of Bot Framework. I'll keep this issue open but will take the issue as a note to make it clearer that the article is out of date and point to more up to date resources which are all at: https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-4.0

**Comment by martinkearn** [comment]
Have updated article to make it clear that the entire article is out of date content. Thanks
